"""Fix user/enrollment relationships

Revision ID: 20e2e889ed0e
Revises: 9613171ba68b
Create Date: 2025-11-01 15:10:52.630641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e2e889ed0e'
down_revision = '9613171ba68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_completed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('date_completed')

    # ### end Alembic commands ###
