"""Add login streak fields

Revision ID: aee17bce7c4e
Revises: 20e2e889ed0e
Create Date: 2025-11-09 11:23:24.996072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee17bce7c4e'
down_revision = '20e2e889ed0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_last_active', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('login_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_streak')
        batch_op.drop_column('streak_last_active')

    # ### end Alembic commands ###
